### ISSUE TITLE
RHEL7 config branch fails with compilation error

### ISSUE THREAD

**Issue by belminf** [bodgit/puppet-rngd#4]
Receive error such as:

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Files must be fully qualified at /etc/puppet/environments/boris/rngd/manifests/config.pp:42 on node bf_t128393_xy.example.com

Tested on RHEL5 and RHEL6 without similar issue.

**Comment by bodgit** [comment]
The behaviour won't trigger on RHEL5 or RHEL6 as they don't have Systemd however I'm struggling to work out how you're getting that behaviour anyway. The function is being used exactly as it should, see [here](https://docs.puppet.com/puppet/latest/reference/function.html#file) for the function reference. The function _can_ accept fully qualified filenames but it's not mandatory so that error doesn't match the documentation.

What version(s) of Puppet are you running?

**Comment by belminf** [comment]
The error is on Puppet 3.6.2 (latest Satellite agent for RHEL7). I'll dig deeper in a bit.

**Comment by bodgit** [comment]
Ah, I don't think I've ever tried that old a release of Puppet, I'm surprised RHEL are still on that old a release given the latest version is **4**.6.2 now.

Pinning the Puppet gem to 3.6.2 reproduces the error, upgrading to even just 3.7.x fixes things, looking at the documentation changes between those releases shows the `file()` function received some updates.

Given I'm claiming support for 3.0.0 and I'm primarily focused on RHEL as a general rule I'll fix this up as it's only one occurrence.

**Comment by bodgit** [comment]
v1.1.1 is up on the forge now that should fix this, thanks for the bug report!

**Comment by belminf** [comment]
Thank you for the prompt response!
